version: "3"
services:
  vendor-portal:
    image: marklen1984/selenium
    environment:
    - BROWSER=chrome
    - HUB_HOST=hub
    - THREAD_COUNT=3
    - TEST_SUITE=vendor-portal.xml
    volumes:
    - C:\Users\Mark\Education\xyz\selenium-docker05\-dockerize03-providing-test-data\test-data\output\vendor-portal:/home/selenium-docker/test-output

  flight-reservation:
    image: marklen1984/selenium
    environment:
    - BROWSER=firefox
    - HUB_HOST=hub
    - THREAD_COUNT=4
    - TEST_SUITE=flight-reservation.xml
    volumes:
    - C:\Users\Mark\Education\xyz\selenium-docker05\-dockerize03-providing-test-data\test-data\output\flight-reservation:/home/selenium-docker/test-output     